# Generated by Django 3.0.6 on 2020-06-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('ufather', models.CharField(max_length=30)),
                ('umob', models.IntegerField()),
                ('upw', models.CharField(max_length=10)),
                ('unpanchayat', models.CharField(max_length=15)),
                ('ugram', models.CharField(max_length=15)),
            ],
        ),
    ]
