# Generated by Django 3.0.6 on 2020-06-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cmob', models.IntegerField()),
                ('unpanchayat', models.CharField(max_length=15)),
                ('cdepart', models.CharField(max_length=15)),
                ('csub', models.CharField(max_length=15)),
                ('cdescrip', models.CharField(max_length=100)),
            ],
        ),
    ]
