# Generated by Django 3.0.6 on 2020-06-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_complain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='unpanchayat',
            new_name='cnpanchayat',
        ),
    ]
