# Generated by Django 3.0.6 on 2020-06-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200624_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='firstname',
            field=models.TextField(default=0, max_length=15),
        ),
    ]
