# Generated by Django 3.0.6 on 2020-06-25 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_auto_20200624_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaindata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
                ('gram_nagar', models.CharField(max_length=30)),
                ('com_subject', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('upload_file', models.FileField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
