# Generated by Django 3.0.6 on 2020-06-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_complaindata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaindata',
            name='department',
            field=models.CharField(default='a', max_length=30),
        ),
    ]
