# Generated by Django 3.0.6 on 2020-06-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200626_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='firname',
            field=models.TextField(max_length=15),
        ),
    ]
