# Generated by Django 3.0.6 on 2020-10-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200627_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaindata',
            name='department',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='complaindata',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
