# Generated by Django 3.0.6 on 2020-10-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20201002_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaindata',
            name='status',
            field=models.CharField(default='Recieved', max_length=100),
        ),
    ]
